mail:
  smtp:
    host: smtp.qq.com
    auth: true
  sender:
    mailbox:
      account: person-working@qq.com
      nickname: 人工智能对话 用户服务
      secret: czghbgzdigtccifj
  verification-code:
    #    template: 尊敬的 %s (%s) 您好，欢迎使用Person Working个人网盘服务。您的验证码是 %d ，请在 %d 分钟内完成账户验证。如不是您本人操作请忽略，谢谢。
    template: 尊敬的 %s (%s) 本次服务验证码是 %d 。请在 %d 分钟内完成验证。
    timeout: 10
    # 一个邮箱一小时内发送邮件的次数限制
    mailbox-limit: 10
    # 一个ip地址一小时内发送邮件的次数限制
    ip-limit: 10
